{"bbac940aa4d324295a100c1613084ff1":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"68ffb4de7672bdc2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1073968e0>: Failed to establish a new connection: [Errno 61] Connection refused'))","time":{"start":1690252026847,"stop":1690252026849,"duration":2}}]},"ad577ed772a7c74555da8db782265ad9":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"f5b3289d38107dea","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at XCUITestDriver.doNativeFind (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:143:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at XCUITestDriver.findNativeElementOrElements (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:97:12)\n    at XCUITestDriver.findElOrEls (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:24:14)\n    at XCUITestDriver.findElOrElsWithProcessing (/Users/57block/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at XCUITestDriver.findElement (/Users/57block/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)","time":{"start":1690252035216,"stop":1690252047261,"duration":12045}}]},"d75c4dcda674153883fc6288ff86a74e":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"ed362e86d1cc5a42","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10743bac0>: Failed to establish a new connection: [Errno 61] Connection refused'))","time":{"start":1690252026152,"stop":1690252026154,"duration":2}}]}}