{"bbac940aa4d324295a100c1613084ff1":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"430a83c600dd089f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107bdbca0>: Failed to establish a new connection: [Errno 61] Connection refused'))","time":{"start":1690252107737,"stop":1690252107740,"duration":3}}]},"d75c4dcda674153883fc6288ff86a74e":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"757ad21ce47c77b1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107eaaee0>: Failed to establish a new connection: [Errno 61] Connection refused'))","time":{"start":1690252106948,"stop":1690252106951,"duration":3}}]}}