{"name": "test3_follow_list", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at XCUITestDriver.doNativeFind (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:143:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at XCUITestDriver.findNativeElementOrElements (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:97:12)\n    at XCUITestDriver.findElOrEls (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:24:14)\n    at XCUITestDriver.findElOrElsWithProcessing (/Users/57block/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at XCUITestDriver.findElement (/Users/57block/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)", "trace": "self = <test_follow.TestFollow testMethod=test3_follow_list>\n\n    def setUp(self) -> None:\n        self.driver = get_driver()\n        global do\n        do = Actions(self.driver)\n>       do.login_flow(test_account)\n\ntestcase/profile/test_follow.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nutils/user_actions.py:727: in login_flow\n    self.assert_element(home, 'success login')\nutils/user_actions.py:776: in assert_element\n    raise e\nutils/user_actions.py:773: in assert_element\n    assert get_element(self.driver, locator, wait_time)\nutils/find_element.py:12: in get_element\n    raise e\nutils/find_element.py:6: in get_element\n    element = WebDriverWait(driver, wait_time).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"969e1f65-2ab9-45a4-b8e3-cc6524b872f0\")>\nmethod = <function get_element.<locals>.<lambda> at 0x10654c790>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       NoSuchElementError: An element could not be located on the page using the given search parameters.\nE           at XCUITestDriver.doNativeFind (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:143:13)\nE           at processTicksAndRejections (node:internal/process/task_queues:95:5)\nE           at XCUITestDriver.findNativeElementOrElements (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:97:12)\nE           at XCUITestDriver.findElOrEls (/Users/57block/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:24:14)\nE           at XCUITestDriver.findElOrElsWithProcessing (/Users/57block/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\nE           at XCUITestDriver.findElement (/Users/57block/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException"}, "start": 1690964456850, "stop": 1690964477214, "uuid": "887d2e34-57f8-4bb4-830c-77e6b502f2f5", "historyId": "00f762124aa6955a8ac0c18c8f47f896", "testCaseId": "00f762124aa6955a8ac0c18c8f47f896", "fullName": "testcase.profile.test_follow.TestFollow#test3_follow_list", "labels": [{"name": "story", "value": "Empty list"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "Follow"}, {"name": "parentSuite", "value": "testcase.profile"}, {"name": "suite", "value": "test_follow"}, {"name": "subSuite", "value": "TestFollow"}, {"name": "host", "value": "Joys-MacBook-Pro.local"}, {"name": "thread", "value": "28553-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.profile.test_follow"}]}